// Code generated by controller generator. DO NOT EDIT.

package controllers

import (
	"github.com/ArcherChu123/plugin-daemon/internal/service"
	"github.com/ArcherChu123/plugin-daemon/internal/types/app"
	"github.com/ArcherChu123/plugin-daemon/pkg/entities/plugin_entities"
	"github.com/ArcherChu123/plugin-daemon/pkg/entities/requests"
	"github.com/gin-gonic/gin"
)

func InvokeAgentStrategy(config *app.Config) gin.HandlerFunc {
	type request = plugin_entities.InvokePluginRequest[requests.RequestInvokeAgentStrategy]

	return func(c *gin.Context) {
		BindPluginDispatchRequest(
			c,
			func(itr request) {
				service.InvokeAgentStrategy(&itr, c, config.PluginMaxExecutionTimeout)
			},
		)
	}
}
